// Bible references suggestions for different liturgy sections
export const bibleReferenceSuggestions = {
  worshipCall: [
    'Salmo 95:1-7 - "Vinde, cantemos alegremente ao SENHOR, com júbilo celebremos o Rochedo da nossa salvação. Apresentemo-nos diante dele com ações de graças, celebremo-lo com salmos. Porque o SENHOR é o Deus supremo e o grande Rei acima de todos os deuses..."',
    'Salmo 100 - "Celebrai com júbilo ao SENHOR, todas as terras. Servi ao SENHOR com alegria, apresentai-vos diante dele com cântico. Sabei que o SENHOR é Deus; foi ele quem nos fez, e dele somos; somos o seu povo e rebanho do seu pastoreio..."',
    'Isaías 55:1-3 - "Ah! Todos vós, os que tendes sede, vinde às águas; e vós, os que não tendes dinheiro, vinde, comprai e comei; sim, vinde e comprai, sem dinheiro e sem preço, vinho e leite..."',
    'Salmo 96:1-9 - "Cantai ao SENHOR um cântico novo, cantai ao SENHOR, todas as terras. Cantai ao SENHOR, bendizei o seu nome; proclamai a sua salvação, dia após dia..."',
    'Salmo 98:1-6 - "Cantai ao SENHOR um cântico novo, porque ele tem feito maravilhas; a sua destra e o seu braço santo lhe alcançaram a vitória..."',
    'Salmo 122:1 - "Alegrei-me quando me disseram: Vamos à Casa do SENHOR..."',
    'Salmo 34:1-3 - "Bendirei o SENHOR em todo o tempo, o seu louvor estará sempre nos meus lábios. Gloriar-se-á no SENHOR a minha alma; os humildes o ouvirão e se alegrarão. Engrandecei o SENHOR comigo, e todos, à uma, lhe exaltemos o nome..."',
    'Salmo 84:1-4 - "Quão amáveis são os teus tabernáculos, SENHOR dos Exércitos! A minha alma suspira e desfalece pelos átrios do SENHOR; o meu coração e a minha carne exultam pelo Deus vivo!..."',
    'Salmo 63:1-4 - "Ó Deus, tu és o meu Deus forte; eu te busco ansiosamente; a minha alma tem sede de ti; o meu corpo te almeja, como terra árida, exausta, sem água..."',
    'Salmo 95:6-7 - "Vinde, adoremos e prostremo-nos; ajoelhemos diante do SENHOR, que nos criou. Ele é o nosso Deus, e nós, povo do seu pasto e ovelhas de sua mão..."',
    'Apocalipse 4:11 - "Tu és digno, Senhor e Deus nosso, de receber a glória, a honra e o poder, porque todas as coisas tu criaste, sim, por causa da tua vontade vieram a existir e foram criadas..."',
    'Apocalipse 15:3-4 - "Cantavam o cântico de Moisés, servo de Deus, e o cântico do Cordeiro, dizendo: Grandes e admiráveis são as tuas obras, Senhor Deus, Todo-Poderoso! Justos e verdadeiros são os teus caminhos, ó Rei das nações!..."',
    'Salmo 86:8-10 - "Não há semelhante a ti entre os deuses, ó Senhor, e não há obras como as tuas. Todas as nações que fizeste virão à tua presença, Senhor, e se prostrarão diante de ti, e glorificarão o teu nome..."',
    'Salmo 66:1-4 - "Aclamai a Deus, toda a terra. Cantai a glória do seu nome, dai glória em seu louvor. Dizei a Deus: Quão tremendas são as tuas obras! Pela grandeza do teu poder, os teus inimigos te prestam obediência..."',
    'Habacuque 2:20 - "O SENHOR, porém, está no seu santo templo; cale-se diante dele toda a terra..."',
    'Salmo 118:24-29 - "Este é o dia que o SENHOR fez; regozijemo-nos e alegremo-nos nele. Salva-nos, agora, SENHOR! Ó SENHOR, concede-nos prosperidade!..."',
    'Salmo 135:1-3 - "Aleluia! Louvai o nome do SENHOR; louvai-o, servos do SENHOR, vós que assistis na Casa do SENHOR, nos átrios da casa do nosso Deus..."',
    'Isaías 6:1-3 - "No ano da morte do rei Uzias, eu vi o Senhor assentado sobre um alto e sublime trono, e as abas de suas vestes enchiam o templo. Serafins estavam por cima dele; cada um tinha seis asas; com duas cobria o rosto, com duas cobria os seus pés e com duas voava..."',
    'Salmo 145:1-7 - "Exaltar-te-ei, ó Deus meu e Rei; bendirei o teu nome para todo o sempre. Todos os dias te bendirei e louvarei o teu nome para todo o sempre..."',
    'Hebreus 12:28-29 - "Por isso, recebendo nós um reino inabalável, retenhamos a graça, pela qual sirvamos a Deus de modo agradável, com reverência e santo temor; porque o nosso Deus é fogo consumidor..."',
  ],
  lawReading: [
    'Êxodo 20:1-17 - "Então, falou Deus todas estas palavras: Eu sou o SENHOR, teu Deus, que te tirei da terra do Egito, da casa da servidão. Não terás outros deuses diante de mim..."',
    'Deuteronômio 5:6-21 - "Eu sou o SENHOR, teu Deus, que te tirei da terra do Egito, da casa da servidão. Não terás outros deuses diante de mim..."',
    'Mateus 22:37-40 - "Respondeu-lhe Jesus: Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu entendimento. Este é o grande e primeiro mandamento. O segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo..."',
    'Romanos 13:8-10 - "A ninguém fiqueis devendo coisa alguma, exceto o amor com que vos ameis uns aos outros; pois quem ama o próximo tem cumprido a lei..."',
    'Gálatas 5:13-14 - "Porque vós, irmãos, fostes chamados à liberdade; porém não useis da liberdade para dar ocasião à carne; sede, antes, servos uns dos outros, pelo amor..."',
    'Tiago 2:8-13 - "Se vós, contudo, observais a lei régia segundo a Escritura: Amarás o teu próximo como a ti mesmo, fazeis bem..."',
    'Levítico 19:1-4 - "Disse o SENHOR a Moisés: Fala a toda a congregação dos filhos de Israel e dize-lhes: Santos sereis, porque eu, o SENHOR, vosso Deus, sou santo..."',
    'Deuteronômio 6:4-9 - "Ouve, Israel, o SENHOR, nosso Deus, é o único SENHOR. Amarás, pois, o SENHOR, teu Deus, de todo o teu coração, de toda a tua alma e de toda a tua força..."',
    'Mateus 5:17-20 - "Não penseis que vim revogar a Lei ou os Profetas; não vim para revogar, vim para cumprir. Porque em verdade vos digo: até que o céu e a terra passem, nem um i ou um til jamais passará da Lei, até que tudo se cumpra..."',
    'Mateus 7:12 - "Tudo quanto, pois, quereis que os homens vos façam, assim fazei-o vós também a eles; porque esta é a Lei e os Profetas..."',
    '1 João 4:19-21 - "Nós amamos porque ele nos amou primeiro. Se alguém disser: Amo a Deus, e odiar a seu irmão, é mentiroso; pois aquele que não ama a seu irmão, a quem vê, não pode amar a Deus, a quem não vê..."',
    'João 14:15,21 - "Se me amais, guardareis os meus mandamentos... Aquele que tem os meus mandamentos e os guarda, esse é o que me ama; e aquele que me ama será amado por meu Pai, e eu também o amarei e me manifestarei a ele..."',
    'Miquéias 6:8 - "Ele te declarou, ó homem, o que é bom; e que é o que o SENHOR pede de ti, senão que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus?..."',
    'Êxodo 34:6-7 - "O SENHOR passou diante dele e proclamou: SENHOR, SENHOR Deus compassivo, clemente e longânimo e grande em misericórdia e fidelidade; que guarda a misericórdia em mil gerações, que perdoa a iniquidade, a transgressão e o pecado..."',
    'Salmo 19:7-11 - "A lei do SENHOR é perfeita e restaura a alma; o testemunho do SENHOR é fiel e dá sabedoria aos símplices. Os preceitos do SENHOR são retos e alegram o coração; o mandamento do SENHOR é puro e ilumina os olhos..."',
    'Salmo 119:1-8 - "Bem-aventurados os irrepreensíveis no seu caminho, que andam na lei do SENHOR. Bem-aventurados os que guardam as suas prescrições e o buscam de todo o coração..."',
    'Romanos 7:12-14 - "Por conseguinte, a lei é santa; e o mandamento, santo, e justo, e bom. Acaso o bom se me tornou em morte? De modo nenhum; pelo contrário, o pecado, para revelar-se como pecado, por meio do que é bom, causou-me a morte..."',
    'Mateus 5:21-30 - "Ouvistes que foi dito aos antigos: Não matarás; e: Quem matar estará sujeito a julgamento. Eu, porém, vos digo que todo aquele que sem motivo se irar contra seu irmão estará sujeito a julgamento..."',
    'Gálatas 3:24-25 - "De maneira que a lei nos serviu de aio para nos conduzir a Cristo, a fim de que fôssemos justificados por fé. Mas, tendo vindo a fé, já não permanecemos subordinados ao aio..."',
    'Hebreus 8:10 - "Porque esta é a aliança que firmarei com a casa de Israel, depois daqueles dias, diz o Senhor: Na sua mente imprimirei as minhas leis, também sobre o seu coração as inscreverei; e eu serei o seu Deus, e eles serão o meu povo..."',
  ],
  forgiveness: [
    'Salmo 32:1-5 - "Bem-aventurado aquele cuja iniquidade é perdoada, cujo pecado é coberto. Bem-aventurado o homem a quem o SENHOR não atribui iniquidade e em cujo espírito não há dolo..."',
    'Isaías 1:18 - "Vinde, pois, e arrazoemos, diz o SENHOR; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a lã..."',
    'Isaías 43:25 - "Eu, eu mesmo, sou o que apago as tuas transgressões por amor de mim e dos teus pecados não me lembro..."',
    '1 João 1:9 - "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça..."',
    'Romanos 5:1-2 - "Justificados, pois, mediante a fé, temos paz com Deus por meio de nosso Senhor Jesus Cristo; por intermédio de quem obtivemos igualmente acesso, pela fé, a esta graça na qual estamos firmes; e gloriamo-nos na esperança da glória de Deus..."',
    'Colossenses 1:13-14 - "Ele nos libertou do império das trevas e nos transportou para o reino do Filho do seu amor, no qual temos a redenção, a remissão dos pecados..."',
    'Efésios 1:7-8 - "No qual temos a redenção, pelo seu sangue, a remissão dos pecados, segundo a riqueza da sua graça, que Deus derramou abundantemente sobre nós em toda a sabedoria e prudência..."',
    'Miquéias 7:18-19 - "Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade e te esqueces da transgressão do restante da tua herança? O SENHOR não retém a sua ira para sempre, porque tem prazer na misericórdia..."',
    'Salmo 103:8-12 - "O SENHOR é misericordioso e compassivo, longânimo e assaz benigno. Não repreende perpetuamente, nem conserva para sempre a sua ira. Não nos trata segundo os nossos pecados, nem nos retribui consoante as nossas iniquidades..."',
    'Salmo 51:1-10 - "Compadece-te de mim, ó Deus, segundo a tua benignidade; e, segundo a multidão das tuas misericórdias, apaga as minhas transgressões. Lava-me completamente da minha iniquidade e purifica-me do meu pecado..."',
    'Lucas 15:20-24 - "E, levantando-se, foi para seu pai. Estando ele ainda longe, viu-o seu pai, e se comoveu de compaixão, e, correndo, lançou-se-lhe ao pescoço e o beijou..."',
    'Atos 10:43 - "Dele todos os profetas dão testemunho de que, por meio de seu nome, todo aquele que nele crê recebe remissão de pecados..."',
    'Efésios 2:4-5 - "Mas Deus, sendo rico em misericórdia, por causa do grande amor com que nos amou, estando nós ainda mortos em nossos delitos, nos deu vida juntamente com Cristo, pela graça sois salvos..."',
    'Isaías 44:22 - "Desfaço as tuas transgressões como a névoa, e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi..."',
    'Romanos 8:1-2 - "Agora, pois, já nenhuma condenação há para os que estão em Cristo Jesus. Porque a lei do Espírito da vida, em Cristo Jesus, te livrou da lei do pecado e da morte..."',
    'Tito 3:4-7 - "Quando, porém, se manifestou a benignidade de Deus, nosso Salvador, e o seu amor para com todos, não por obras de justiça praticadas por nós, mas segundo sua misericórdia, ele nos salvou..."',
    '2 Coríntios 5:17-19 - "E, assim, se alguém está em Cristo, é nova criatura; as coisas antigas já passaram; eis que se fizeram novas. Ora, tudo provém de Deus, que nos reconciliou consigo mesmo por meio de Cristo..."',
    'Hebreus 10:17-18 - "Acrescenta: Também jamais me lembrarei dos seus pecados e das suas iniquidades. Ora, onde há remissão destes, não há mais oferta pelo pecado..."',
    'Salmo 130:3-4 - "Se observares, SENHOR, iniquidades, quem, Senhor, subsistirá? Contigo, porém, está o perdão, para que te temam..."',
    'Joel 2:12-13 - "Ainda assim, agora mesmo, diz o SENHOR: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, com choro e com pranto. Rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao SENHOR, vosso Deus..."',
  ],
  intercession: [
    '1 Timóteo 2:1-4 - "Antes de tudo, recomendo que se façam súplicas, orações, intercessões e ações de graças por todos os homens; pelos reis e por todos os que se acham investidos de autoridade, para que vivamos vida tranquila e mansa, com toda piedade e respeito..."',
    'Filipenses 4:6-7 - "Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas, diante de Deus, as vossas petições, pela oração e pela súplica, com ações de graças..."',
    'Tiago 5:13-16 - "Está alguém entre vós sofrendo? Faça oração. Está alguém alegre? Cante louvores. Está alguém entre vós doente? Chame os presbíteros da igreja, e estes façam oração sobre ele, ungindo-o com óleo, em nome do Senhor..."',
    'Mateus 6:9-13 - "Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome; venha o teu reino; faça-se a tua vontade, assim na terra como no céu..."',
    'Colossenses 1:9-12 - "Por esta razão, também nós, desde o dia em que o ouvimos, não cessamos de orar por vós e de pedir que transbordeis de pleno conhecimento da sua vontade, em toda a sabedoria e entendimento espiritual..."',
    'Romanos 8:26-27 - "Também o Espírito, semelhantemente, nos assiste em nossa fraqueza; porque não sabemos orar como convém, mas o mesmo Espírito intercede por nós sobremaneira, com gemidos inexprimíveis..."',
    'Efésios 6:18-20 - "Com toda oração e súplica, orando em todo tempo no Espírito e para isto vigiando com toda perseverança e súplica por todos os santos e também por mim; para que me seja dada, no abrir da minha boca, a palavra, para, com intrepidez, fazer conhecido o mistério do evangelho..."',
    'João 17:20-21 - "Não rogo somente por estes, mas também por aqueles que vierem a crer em mim, por intermédio da sua palavra; a fim de que todos sejam um; e como és tu, ó Pai, em mim e eu em ti, também sejam eles em nós; para que o mundo creia que tu me enviaste..."',
    'Isaías 59:16 - "Viu que não havia ajudador e maravilhou-se de que não houvesse um intercessor; pelo que o seu próprio braço lhe trouxe a salvação, e a sua própria justiça o susteve..."',
    '1 Samuel 12:23 - "Quanto a mim, longe de mim que eu peque contra o SENHOR, deixando de orar por vós; antes, vos ensinarei o caminho bom e direito..."',
    'Atos 12:5 - "Pedro, pois, estava guardado no cárcere; mas havia oração incessante a Deus por parte da igreja a favor dele..."',
    'Romanos 15:30-32 - "Rogo-vos, pois, irmãos, por nosso Senhor Jesus Cristo e também pelo amor do Espírito, que luteis juntamente comigo nas orações a Deus a meu favor..."',
    'Hebreus 7:25 - "Por isso, também pode salvar totalmente os que por ele se chegam a Deus, vivendo sempre para interceder por eles..."',
    'Daniel 9:3-19 - "Voltei o rosto ao Senhor Deus, para o buscar com oração e súplicas, com jejum, pano de saco e cinza. Orei ao SENHOR, meu Deus, confessei e disse: Ah! Senhor, Deus grande e temível..."',
    'Gênesis 18:23-33 - "Aproximou-se Abraão e disse: Destruirás o justo com o ímpio? Se houver cinquenta justos na cidade, destruirás e não pouparás o lugar por amor dos cinquenta justos que nele se encontram?..."',
    'João 14:13-14 - "E tudo quanto pedirdes em meu nome, isso farei, a fim de que o Pai seja glorificado no Filho. Se me pedirdes alguma coisa em meu nome, eu o farei..."',
    '2 Crônicas 7:14 - "Se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e me buscar, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, perdoarei os seus pecados e sararei a sua terra..."',
    'Lucas 18:1-8 - "Contou-lhes Jesus uma parábola sobre o dever de orar sempre e nunca esmorecer: Havia em certa cidade um juiz que não temia a Deus, nem respeitava homem algum..."',
    'Ezequiel 22:30 - "Busquei entre eles um homem que levantasse o muro e se colocasse na brecha perante mim a favor desta terra, para que eu não a destruísse; mas a ninguém achei..."',
    'Efésios 3:14-19 - "Por esta causa, me ponho de joelhos diante do Pai, de quem toma o nome toda família, tanto no céu como sobre a terra, para que, segundo a riqueza da sua glória, vos conceda que sejais fortalecidos com poder, mediante o seu Espírito no homem interior..."',
  ],
  // Para a seção illumination:
  illumination: [
    // Referências existentes
    'Salmo 119:105 - "Lâmpada para os meus pés é a tua palavra e, luz para os meus caminhos..."',
    'Provérbios 2:1-5 - "Filho meu, se aceitares as minhas palavras e esconderes contigo os meus mandamentos, para fazeres atento à sabedoria o teu ouvido e para inclinares o coração ao entendimento..."',
    'João 16:12-15 - "Tenho ainda muito que vos dizer, mas vós não o podeis suportar agora; quando vier, porém, o Espírito da verdade, ele vos guiará a toda a verdade; porque não falará por si mesmo, mas dirá tudo o que tiver ouvido e vos anunciará as coisas que hão de vir..."',
    '2 Timóteo 3:16-17 - "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a educação na justiça, a fim de que o homem de Deus seja perfeito e perfeitamente habilitado para toda boa obra..."',
    'Hebreus 4:12 - "Porque a palavra de Deus é viva, e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até ao ponto de dividir alma e espírito, juntas e medulas, e é apta para discernir os pensamentos e propósitos do coração..."',
    'Efésios 1:17-19 - "Para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos conceda espírito de sabedoria e de revelação no pleno conhecimento dele, iluminados os olhos do vosso coração..."',
    // Novas referências
    'Salmo 119:18 - "Desvenda os meus olhos, para que eu contemple as maravilhas da tua lei..."',
    'Lucas 24:45 - "Então, lhes abriu o entendimento para compreenderem as Escrituras..."',
    'Salmo 19:8 - "Os preceitos do SENHOR são retos e alegram o coração; o mandamento do SENHOR é puro e ilumina os olhos..."',
    'João 14:26 - "Mas o Consolador, o Espírito Santo, a quem o Pai enviará em meu nome, esse vos ensinará todas as coisas e vos fará lembrar de tudo o que vos tenho dito..."',
    '1 Coríntios 2:12-14 - "Ora, nós não recebemos o espírito do mundo, e sim o Espírito que vem de Deus, para que conheçamos o que por Deus nos foi dado gratuitamente..."',
    'Atos 26:17-18 - "...livrando-te do povo e dos gentios, para os quais eu te envio, para lhes abrires os olhos e os converteres das trevas para a luz e da potestade de Satanás para Deus..."',
    'Salmo 43:3 - "Envia a tua luz e a tua verdade, para que me guiem e me levem ao teu santo monte e aos teus tabernáculos..."',
    'Tiago 1:5 - "Se, porém, algum de vós necessita de sabedoria, peça-a a Deus, que a todos dá liberalmente e nada lhes impropera; e ser-lhe-á concedida..."',
    '2 Coríntios 4:6 - "Porque Deus, que disse: Das trevas resplandecerá a luz, ele mesmo resplandeceu em nossos corações, para iluminação do conhecimento da glória de Deus, na face de Cristo..."',
    'Colossenses 1:9 - "Por esta razão, também nós, desde o dia em que o ouvimos, não cessamos de orar por vós e de pedir que transbordeis de pleno conhecimento da sua vontade, em toda a sabedoria e entendimento espiritual..."',
    'Isaías 50:4-5 - "O Senhor Deus me deu língua de eruditos, para que eu saiba dizer boa palavra ao cansado. Ele me desperta todas as manhãs, desperta-me o ouvido para que eu ouça como os eruditos. O Senhor Deus me abriu os ouvidos, e eu não fui rebelde, nem me retirei para trás..."',
    'João 8:31-32 - "Disse, pois, Jesus aos judeus que haviam crido nele: Se vós permanecerdes na minha palavra, sois verdadeiramente meus discípulos; e conhecereis a verdade, e a verdade vos libertará..."',
    'Salmo 119:130 - "A revelação das tuas palavras esclarece e dá entendimento aos simples..."',
    'Provérbios 1:7 - "O temor do SENHOR é o princípio do saber, mas os loucos desprezam a sabedoria e o ensino..."',
  ],

  // Para a seção wordPreaching:
  wordPreaching: [
    // Referências existentes
    'Romanos 10:14-17 - "Como, porém, invocarão aquele em quem não creram? E como crerão naquele de quem nada ouviram? E como ouvirão, se não há quem pregue? E como pregarão, se não forem enviados?..."',
    '2 Timóteo 4:1-5 - "Conjuro-te, perante Deus e Cristo Jesus, que há de julgar vivos e mortos, pela sua manifestação e pelo seu reino: prega a palavra, insta, quer seja oportuno, quer não, corrige, repreende, exorta com toda a longanimidade e doutrina..."',
    'Isaías 55:10-11 - "Porque, assim como descem a chuva e a neve dos céus e para lá não tornam, sem que primeiro reguem a terra, e a fecundem, e a façam brotar, para dar semente ao semeador e pão ao que come, assim será a palavra que sair da minha boca: não voltará para mim vazia..."',
    'Tiago 1:22-25 - "Tornai-vos, pois, praticantes da palavra e não somente ouvintes, enganando-vos a vós mesmos. Porque, se alguém é ouvinte da palavra e não praticante, assemelha-se ao homem que contempla, num espelho, o seu rosto natural..."',
    'Atos 20:27-28 - "Porquanto jamais deixei de vos anunciar todo o desígnio de Deus. Atendei por vós e por todo o rebanho sobre o qual o Espírito Santo vos constituiu bispos, para pastoreardes a igreja de Deus, a qual ele comprou com o seu próprio sangue..."',
    // Novas referências
    '1 Coríntios 1:18-21 - "Certamente, a palavra da cruz é loucura para os que se perdem, mas para nós, que somos salvos, poder de Deus. Pois está escrito: Destruirei a sabedoria dos sábios e aniquilarei a inteligência dos instruídos..."',
    '1 Tessalonicenses 2:13 - "Também, por isso, incessantemente damos graças a Deus, porquanto, ao receberdes a palavra que de nós ouvistes, que é de Deus, acolhestes não como palavra de homens, e sim como, em verdade é, a palavra de Deus, a qual, com efeito, está operando eficazmente em vós, os que credes..."',
    'Romanos 1:16 - "Pois não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê, primeiro do judeu e também do grego..."',
    'Jeremias 23:28-29 - "O profeta que tem um sonho conte o sonho; e aquele que tem a minha palavra anuncie fielmente a minha palavra. Que tem a palha com o trigo? diz o SENHOR. Não é a minha palavra como fogo, diz o SENHOR, e como um martelo que esmiúça a penha?..."',
    'Colossenses 3:16 - "Habite, ricamente, em vós a palavra de Cristo; instruí-vos e aconselhai-vos mutuamente em toda a sabedoria, louvando a Deus, com salmos, e hinos, e cânticos espirituais, com gratidão, em vosso coração..."',
    'Hebreus 13:7 - "Lembrai-vos dos vossos guias, os quais vos pregaram a palavra de Deus, e, considerando atentamente o fim da sua vida, imitai a fé que tiveram..."',
    '1 Pedro 1:23-25 - "Pois fostes regenerados não de semente corruptível, mas de incorruptível, mediante a palavra de Deus, a qual vive e é permanente. Pois toda carne é como a erva, e toda a sua glória, como a flor da erva; seca-se a erva, e cai a sua flor; a palavra do Senhor, porém, permanece eternamente..."',
    'Atos 6:4 - "Mas nós perseveraremos na oração e no ministério da palavra..."',
    'Neemias 8:8 - "E leram no livro, na lei de Deus, distintamente, e deram o sentido, e fizeram que, lendo, se entendesse..."',
    'Mateus 4:4 - "Jesus, porém, respondeu: Está escrito: Não só de pão viverá o homem, mas de toda palavra que procede da boca de Deus..."',
    'Ezequiel 3:17-19 - "Filho do homem, eu te dei por atalaia sobre a casa de Israel; da minha boca ouvirás a palavra e avisá-los-ás da minha parte..."',
    'Atos 17:11 - "Ora, estes de Beréia eram mais nobres que os de Tessalônica; pois receberam a palavra com toda a avidez, examinando as Escrituras todos os dias para ver se as coisas eram, de fato, assim..."',
    '2 Timóteo 2:15 - "Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade..."',
    'Lucas 8:15 - "A que caiu em boa terra são os que, tendo ouvido de bom e reto coração, retêm a palavra; estes frutificam com perseverança..."',
    'Marcos 4:20 - "E os que foram semeados em boa terra são aqueles que ouvem a palavra e a recebem, e dão fruto a trinta, a sessenta e a cem por um..."',
  ],

  // Para a seção lordsSupper:
  lordsSupper: [
    // Referências existentes
    '1 Coríntios 11:23-26 - "Porque eu recebi do Senhor o que também vos entreguei: que o Senhor Jesus, na noite em que foi traído, tomou o pão; e, tendo dado graças, o partiu e disse: Isto é o meu corpo, que é dado por vós; fazei isto em memória de mim..."',
    'Marcos 14:22-25 - "Enquanto comiam, tomou Jesus um pão e, abençoando-o, o partiu e lhes deu, dizendo: Tomai, isto é o meu corpo. A seguir, tomou Jesus um cálice e, tendo dado graças, o deu aos seus discípulos; e todos beberam dele..."',
    'Lucas 22:14-20 - "Chegada a hora, pôs-se Jesus à mesa, e com ele os apóstolos. E disse-lhes: Tenho desejado ansiosamente comer convosco esta Páscoa, antes do meu sofrimento..."',
    'João 6:35-40 - "Declarou-lhes, pois, Jesus: Eu sou o pão da vida; o que vem a mim jamais terá fome; e o que crê em mim jamais terá sede..."',
    '1 Coríntios 10:16-17 - "Porventura, o cálice da bênção que abençoamos não é a comunhão do sangue de Cristo? O pão que partimos não é a comunhão do corpo de Cristo? Porque nós, embora muitos, somos unicamente um pão, um só corpo; porque todos participamos do único pão..."',
    // Novas referências
    'João 6:53-56 - "Respondeu-lhes Jesus: Em verdade, em verdade vos digo: se não comerdes a carne do Filho do Homem e não beberdes o seu sangue, não tendes vida em vós mesmos. Quem comer a minha carne e beber o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia..."',
    'Mateus 26:26-28 - "Enquanto comiam, tomou Jesus um pão, e, abençoando-o, o partiu, e o deu aos discípulos, dizendo: Tomai, comei; isto é o meu corpo. A seguir, tomou um cálice e, tendo dado graças, o deu aos discípulos, dizendo: Bebei dele todos; porque isto é o meu sangue, o sangue da nova aliança, derramado em favor de muitos, para remissão de pecados..."',
    '1 Coríntios 11:27-29 - "Por isso, aquele que comer o pão ou beber o cálice do Senhor, indignamente, será réu do corpo e do sangue do Senhor. Examine-se, pois, o homem a si mesmo, e, assim, coma do pão, e beba do cálice; pois quem come e bebe sem discernir o corpo, come e bebe juízo para si..."',
    'Êxodo 12:14 - "Este dia vos será por memorial, e o celebrareis como solenidade ao SENHOR; nas vossas gerações o celebrareis por estatuto perpétuo..."',
    'Êxodo 24:8 - "Então, tomou Moisés aquele sangue, e o aspergiu sobre o povo, e disse: Eis aqui o sangue da aliança que o SENHOR fez convosco, por meio de todas estas palavras..."',
    'Hebreus 9:15 - "Por isso mesmo, ele é o Mediador da nova aliança, a fim de que, intervindo a morte para remissão das transgressões que havia sob a primeira aliança, recebam a promessa da eterna herança aqueles que têm sido chamados..."',
    'João 6:51 - "Eu sou o pão vivo que desceu do céu; se alguém dele comer, viverá eternamente; e o pão que eu darei pela vida do mundo é a minha carne..."',
    'Atos 2:42 - "E perseveravam na doutrina dos apóstolos e na comunhão, no partir do pão e nas orações..."',
    '1 Coríntios 11:33-34 - "Assim, pois, irmãos meus, quando vos reunis para comer, esperai uns pelos outros. Se alguém tem fome, coma em casa, a fim de não vos reunirdes para juízo..."',
    'Hebreus 13:10 - "Temos um altar do qual não têm direito de comer os que ministram no tabernáculo..."',
    '1 Coríntios 5:7-8 - "Lançai fora o velho fermento, para que sejais nova massa, como sois, de fato, sem fermento. Pois também Cristo, nosso Cordeiro pascal, foi imolado. Por isso, celebremos a festa não com o velho fermento, nem com o fermento da malícia e da maldade, e sim com os asmos da sinceridade e da verdade..."',
    'Salmo 116:12-13 - "Que darei eu ao SENHOR por todos os seus benefícios para comigo? Tomarei o cálice da salvação e invocarei o nome do SENHOR..."',
    'Isaías 25:6 - "O SENHOR dos Exércitos dará neste monte a todos os povos um banquete de pratos suculentos, banquete de vinhos velhos, pratos gordurosos com tutanos e de vinhos velhos, bem clarificados..."',
    'Apocalipse 19:9 - "Então, me falou o anjo: Escreve: Bem-aventurados aqueles que são chamados à ceia das bodas do Cordeiro. E acrescentou: São estas as verdadeiras palavras de Deus..."',
    'Isaías 55:1-3 - "Ah! Todos vós, os que tendes sede, vinde às águas; e vós, os que não tendes dinheiro, vinde, comprai e comei; sim, vinde e comprai, sem dinheiro e sem preço, vinho e leite. Por que gastais o dinheiro naquilo que não é pão, e o vosso suor, naquilo que não satisfaz?..."',
  ],

  // Para a seção consecration:
  consecration: [
    // Referências existentes
    'Romanos 12:1-2 - "Rogo-vos, pois, irmãos, pelas misericórdias de Deus, que apresenteis o vosso corpo por sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional..."',
    '1 Coríntios 10:31 - "Portanto, quer comais, quer bebais ou façais outra coisa qualquer, fazei tudo para a glória de Deus..."',
    'Colossenses 3:16-17 - "Habite, ricamente, em vós a palavra de Cristo; instruí-vos e aconselhai-vos mutuamente em toda a sabedoria, louvando a Deus, com salmos, e hinos, e cânticos espirituais, com gratidão, em vosso coração..."',
    'Malaquias 3:10 - "Trazei todos os dízimos à casa do Tesouro, para que haja mantimento na minha casa; e provai-me nisto, diz o SENHOR dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós bênção sem medida..."',
    '2 Coríntios 9:6-8 - "E isto afirmo: aquele que semeia pouco pouco também ceifará; e o que semeia com fartura com abundância também ceifará. Cada um contribua segundo tiver proposto no coração, não com tristeza ou por necessidade; porque Deus ama a quem dá com alegria..."',
    'Provérbios 3:9-10 - "Honra ao SENHOR com os teus bens e com as primícias de toda a tua renda; e se encherão fartamente os teus celeiros, e transbordarão de vinho os teus lagares..."',
    // Novas referências
    'Hebreus 13:15-16 - "Por meio de Jesus, pois, ofereçamos a Deus, sempre, sacrifício de louvor, que é o fruto de lábios que confessam o seu nome. Não negligencieis, igualmente, a prática do bem e a mútua cooperação; pois, com tais sacrifícios, Deus se compraz..."',
    'Filipenses 4:18 - "Recebi tudo e tenho abundância; estou suprido, desde que Epafrodito me passou às mãos o que me veio de vossa parte como aroma suave, como sacrifício aceitável e aprazível a Deus..."',
    'Gálatas 2:20 - "Logo, já não sou eu quem vive, mas Cristo vive em mim; e esse viver que, agora, tenho na carne, vivo pela fé no Filho de Deus, que me amou e a si mesmo se entregou por mim..."',
    'João 15:4-5 - "Permanecei em mim, e eu permanecerei em vós. Como não pode o ramo produzir fruto de si mesmo, se não permanecer na videira, assim nem vós o podeis dar, se não permanecerdes em mim..."',
    '2 Coríntios 8:1-5 - "Também, irmãos, vos fazemos conhecer a graça de Deus concedida às igrejas da Macedônia; porque, no meio de muita prova de tribulação, manifestaram abundância de alegria, e a profunda pobreza deles superabundou em grande riqueza da sua generosidade..."',
    'Gálatas 5:22-25 - "Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio. Contra estas coisas não há lei..."',
    'Salmo 50:14-15 - "Oferece a Deus sacrifício de ações de graças e cumpre os teus votos para com o Altíssimo; e invoca-me no dia da angústia; eu te livrarei, e tu me glorificarás..."',
    'Salmo 96:8 - "Tributai ao SENHOR a glória devida ao seu nome; trazei oferendas e entrai nos seus átrios..."',
    'Deuteronômio 16:17 - "Cada qual trará a sua oferta conforme as bênçãos que o SENHOR, teu Deus, lhe houver concedido..."',
    '2 Coríntios 8:12 - "Porque, se há boa vontade, será aceita conforme o que o homem tem e não segundo o que ele não tem..."',
    'Lucas 21:1-4 - "Estando Jesus a observar, viu os ricos lançarem suas ofertas no gazofilácio. Viu também certa viúva pobre lançar ali duas pequenas moedas; e disse: Verdadeiramente, vos digo que esta viúva pobre deu mais do que todos..."',
    'Atos 4:34-35 - "Pois nenhum necessitado havia entre eles, porquanto os que possuíam terras ou casas, vendendo-as, traziam os valores correspondentes e depositavam aos pés dos apóstolos; então, se distribuía a qualquer um à medida que alguém tinha necessidade..."',
    'Mateus 5:23-24 - "Se, pois, ao trazeres ao altar a tua oferta, ali te lembrares de que teu irmão tem alguma coisa contra ti, deixa perante o altar a tua oferta, vai primeiro reconciliar-te com teu irmão; e, então, voltando, faze a tua oferta..."',
    'Tiago 1:27 - "A religião pura e sem mácula, para com o nosso Deus e Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e a si mesmo guardar-se incontaminado do mundo..."',
  ],

  // Para a seção sending:
  sending: [
    // Referências existentes
    'Mateus 28:18-20 - "Jesus, aproximando-se, falou-lhes, dizendo: Toda a autoridade me foi dada no céu e na terra. Ide, portanto, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo; ensinando-os a guardar todas as coisas que vos tenho ordenado..."',
    'Atos 1:8 - "Mas recebereis poder, ao descer sobre vós o Espírito Santo, e sereis minhas testemunhas tanto em Jerusalém como em toda a Judéia e Samaria e até aos confins da terra..."',
    'Marcos 16:15 - "E disse-lhes: Ide por todo o mundo e pregai o evangelho a toda criatura..."',
    'Romanos 10:14-15 - "Como, porém, invocarão aquele em quem não creram? E como crerão naquele de quem nada ouviram? E como ouvirão, se não há quem pregue? E como pregarão, se não forem enviados? Como está escrito: Quão formosos são os pés dos que anunciam coisas boas!..."',
    'Josué 1:9 - "Não to mandei eu? Sê forte e corajoso; não temas, nem te espantes, porque o SENHOR, teu Deus, é contigo por onde quer que andares..."',
    // Novas referências
    'João 20:21 - "Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, eu também vos envio..."',
    'Isaías 6:8 - "Depois disto, ouvi a voz do Senhor, que dizia: A quem enviarei, e quem há de ir por nós? Disse eu: eis-me aqui, envia-me a mim..."',
    '2 Coríntios 5:20 - "De sorte que somos embaixadores em nome de Cristo, como se Deus exortasse por nosso intermédio. Em nome de Cristo, pois, rogamos que vos reconcilieis com Deus..."',
    'Lucas 10:1-3 - "Depois disto, designou o Senhor outros setenta; e os enviou de dois em dois, para que o precedessem em cada cidade e lugar aonde ele estava para ir. E lhes dizia: A seara, na verdade, é grande, mas os trabalhadores são poucos. Rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara..."',
    'Isaías 52:7 - "Quão formosos são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia coisas boas, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!..."',
    'Salmo 96:3 - "Proclamai entre as nações a sua glória, entre todos os povos, as suas maravilhas..."',
    'João 17:18 - "Assim como tu me enviaste ao mundo, também eu os enviei ao mundo..."',
    'Mateus 9:37-38 - "Então, disse aos seus discípulos: A seara, na verdade, é grande, mas os trabalhadores são poucos. Rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara..."',
    'Filipenses 2:14-16 - "Fazei todas as coisas sem murmurações nem contendas; para que vos torneis irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio de uma geração perversa e corrupta, na qual resplandeceis como luminares no mundo, preservando a palavra da vida..."',
    'Lucas 24:46-48 - "E lhes disse: Assim está escrito que o Cristo havia de padecer e ressuscitar dentre os mortos no terceiro dia e que em seu nome se pregasse arrependimento para remissão de pecados a todas as nações, começando de Jerusalém. Vós sois testemunhas destas coisas..."',
    'Tiago 1:25 - "Aquele, entretanto, que considera, atentamente, na lei perfeita, lei da liberdade, e nela persevera, não sendo ouvinte negligente, mas operoso praticante, esse será bem-aventurado no que realizar..."',
    'Colossenses 4:5-6 - "Portai-vos com sabedoria para com os que são de fora; aproveitai as oportunidades. A vossa palavra seja sempre agradável, temperada com sal, para saberdes como deveis responder a cada um..."',
    '1 Pedro 3:15 - "Antes, santificai a Cristo, como Senhor, em vosso coração, estando sempre preparados para responder a todo aquele que vos pedir razão da esperança que há em vós, fazendo-o, todavia, com mansidão e temor..."',
    '2 Timóteo 2:24-25 - "Ao servo do Senhor não convém brigar, mas ser brando para com todos, apto para ensinar, paciente, disciplinando com mansidão os que se opõem, na expectativa de que Deus lhes conceda o arrependimento para conhecerem plenamente a verdade..."',
    'Ezequiel 3:17 - "Filho do homem, eu te dei por atalaia sobre a casa de Israel; da minha boca ouvirás a palavra e avisá-los-ás da minha parte..."',
  ],
  blessing: [
    'Números 6:24-26 - "O SENHOR te abençoe e te guarde; o SENHOR faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti; o SENHOR sobre ti levante o seu rosto e te dê a paz..."',
    '2 Coríntios 13:14 - "A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com todos vós..."',
    'Hebreus 13:20-21 - "Ora, o Deus da paz, que tornou a trazer dentre os mortos a Jesus, nosso Senhor, o grande Pastor das ovelhas, pelo sangue da eterna aliança, vos aperfeiçoe em todo bem, para cumprirdes a sua vontade, operando em vós o que é agradável diante dele, por Jesus Cristo, a quem seja a glória para todo o sempre. Amém!..."',
    'Judas 24-25 - "Ora, àquele que é poderoso para vos guardar de tropeços e para vos apresentar com exultação, imaculados diante da sua glória, ao único Deus, nosso Salvador, mediante Jesus Cristo, Senhor nosso, glória, majestade, império e soberania, antes de todas as eras, e agora, e por todos os séculos. Amém!..."',
    'Efésios 3:20-21 - "Ora, àquele que é poderoso para fazer infinitamente mais do que tudo quanto pedimos ou pensamos, conforme o seu poder que opera em nós, a ele seja a glória, na igreja e em Cristo Jesus, por todas as gerações, para todo o sempre. Amém!..."',
    'Romanos 15:13 - "E o Deus da esperança vos encha de todo o gozo e paz no vosso crer, para que sejais ricos de esperança no poder do Espírito Santo..."',
  ],
};
