
// Sugestões de hinos do Novo Cântico organizados por seção litúrgica
export const hymnSuggestions = {
  worshipCall: [
    'NC 1 - Doxologia \n\n Justo é o Senhor em seus santos caminhos,\nBenigno em todas as suas obras. (bis)\nPerto está o Senhor, perto está dos que o invocam,\nDe todos os que o invocam\nEm verdade. Aleluia! Aleluia!\n',
    'NC 2 - Reverência \n\n O Senhor está no seu santo templo!\nO Senhor está no seu santo templo!\nCale-se diante dele toda terra!\nCale-se diante dele toda terra!\n',
    'NC 3 - A Igreja em Adoração \n\n Eterno Pai, teu povo congregado,\nHumilde entoa o teu louvor aqui!\nNo dia para o culto reservado,\nCom esperança olhamos para ti.\nTeu santo livro, ó grande Deus, tomamos\nCom fé singela e reverente amor;\nE, como atentos filhos procuramos\nCiência na palavra do Senhor.\n\nJesus! Aos teus benditos pés sentados\nQueremos teu conselho receber,\nE sendo por ti mesmo doutrinados,\nDe mais em mais na santa fé crescer.\nDo mundo e seus encargos retirados\nQueremos descansar em ti, Senhor,\nMirando os ricos bens entesourados\nNa plenitude do teu vasto amor.\n\nEnsina aos teus, Espírito divino,\nDissipa as trevas destes corações;\nE com a luz do teu celeste ensino\nVem aclarar as santas instruções.\nAviva em nós as forças da memória,\nPois sempre mais queremos conhecer\nO Rei dos céus, o Cristo cuja glória\nEnleva os santos anjos de prazer.\nAmém.\n',
    'NC 4 - Culto à Trindade \n\n Deus está no templo! Pai onipotente!\nA seus pés nos humilhamos.\nServos consagrados, reverentemente,\nAo Deus santo adoramos.\nPor favor, com amor, espiritualmente,\nDeus está no templo!\n\nCristo está no templo! Sumo benefício\nPor seu sangue nos foi dado.\nEle, o bom Cordeiro, foi o sacrifício\nQue expiou o vil pecado.\nEscolheu e sofreu o cabal suplício;\nCristo está no templo!\n\nTu, que estás no templo, preceptor divino,\nE os corações habitas;\nTu, paciente Mestre, dá-nos teu ensino,\nAclarando as leis benditas.\nQue prazer conhecer a graça infinita!\nSim, estás no templo!\nAmém.\n',
    'NC 6 - Doxologia \n\n A Deus, supremo Benfeitor,\nAnjos e homens deem louvor.\nA Deus o Filho, a Deus o Pai,\nE a Deus Espírito, glória dai.\nAmém.\n',
    'NC 7 - Glória à Trindade \n\n A ti, meu Criador,\nDos altos céus Senhor, eu quero honrar.\nAceita a adoração que a voz e o coração\nTe vêm, bondoso Pai, aqui prestar.\n\nA ti, Emanuel,\nPor teu amor fiel rendo eu louvor.\nDo céu trouxeste a luz, por mim sofreste a cruz,\nBendito sejas, pois, meu Redentor.\n\nA ti, Consolador,\nDivino Preceptor, eu louvarei.\nCom teu poder sem par, oh! Vem me iluminar,\nE assim, ao teu fulgor, eu brilharei. Amém.\n',
    'NC 8 - Adoração à Trindade \n\n Grande Deus, o teu louvor hoje, unidos, entoamos;\nTeu excelso e doce amor com os anjos celebramos.\nE em adoração a ti vimos bendizer-te aqui.\n\nCristo, Salvador veraz, com poder em nós domina!\nTua graça e tua paz, ó Senhor, ao mundo ensina.\nRedimido, em tua luz, vem fazê-lo andar, Jesus!\n\nSanto Espírito eternal! Oh! Dirige as nossas mentes\nPara, em comunhão real, te buscarmos reverentes;\nE o nosso coração se encherá de gratidão.\n\nÓ Deus trino, pois a ti sejam, sem cessar, rendidas\nPelos filhos teus aqui, honra e glória sem medida.\nInfinito é o teu amor! Cantem todos teu louvor!\nAmém.\n',
    'NC 9 - Aleluia ao Deus Trino \n\n A ti, ó Deus, altíssimo Senhor,\nEterno Pai, supremo Benfeitor,\nTeus filhos vêm, alegres, dar louvor.\nAleluia! Aleluia!\n\nA ti, Deus Filho, Salvador Jesus,\nDa graça a fonte, da verdade a luz;\nPor teu amor mostrado sobre a cruz,\nAleluia! Aleluia!\n\nA ti, ó Deus, Espírito de amor,\nDe nossas almas santificador.\nMestre divino, bom Consolador,\nAleluia! Aleluia!\n\nÓ tu, Deus Trino, vem nos conceder\nA plenitude do real poder\nE as nossas almas vem, aqui, reger.\nAleluia! Aleluia! Amém.\n',
    'NC 10 - A Criação e Seu Criador \n\n Vós, criaturas de Deus Pai,\nTodos erguei a voz, cantai!\nOh! Louvai-o! Aleluia!\nTu, sol dourado a refulgir,\nTu, lua em prata a reluzir,\nOh! Louvai-o! Oh! Louvai-o!\nAleluia! Aleluia! Aleluia!\n\nOh! Boa terra que nos dás\nInfindas bênçãos, canta já!\nOh! Louvai-o! Aleluia!\nFrutos e flores, juntos dai\nA glória a Deus, Senhor e Pai.\nOh! Louvai-o! Oh! Louvai-o!\nAleluia! Aleluia! Aleluia!\n\nVós, homens sábios e de bem,\nA todos proclamai também!\nOh! Louvai-o! Aleluia!\nLouvor ao Filho, glória ao Pai,\nE ao Santo Espírito louvai!\nOh! Louvai-o! Oh! Louvai-o!\nAleluia! Aleluia! Aleluia!\n',
    'NC 11 - Trindade Santíssima \n\n Santo! Santo! Santo! Deus onipotente!\nLouvam nossas vozes teu nome com fervor!\nSanto! Santo! Santo! Justo e compassivo!\nÉs o Deus trino, excelso criador!\n\nSanto! Santo! Santo! Nós, os pecadores,\nNão podemos ver tua glória sem temor.\nTu somente és santo! Só tu és perfeito,\nDeus soberano, imenso em teu amor.\n\nSanto! Santo! Santo! Todos os remidos,\nJuntos com os anjos, proclamam teu louvor!\nAntes de formar-se o firmamento e a terra\nEras, e sempre és, e hás de ser, Senhor!\n\nSanto! Santo! Santo! Deus onipotente!\nTuas obras louvam teu nome com fervor.\nSanto! Santo! Santo! Justo e compassivo!\nDeus soberano, excelso criador! Amém.\n',
    'NC 12 - Glória a Deus \n\n Santo! Santo! Santo! Deus dos exércitos!\nA terra e os céus proclamam tua glória.\nGlória a ti, glória a ti, ó Deus, eternamente.\nAmém.\n',
    'NC 13 - Contemplação \n\n Se nos cega o sol ardente quando visto em seu fulgor,\nQuem contemplará aquele que do sol é criador?\nPatriarcas não puderam o seu rosto contemplar,\nNem Adão chegou a vê-lo antes mesmo de pecar!\n\nLuz perante a qual é trevas mesmo o sol a fulgurar!\nNossos olhos pecadores não te podem contemplar!\nFogo em cima da arca santa, sarça ardente do Sinai\nSão figuras dessa glória do Senhor e eterno Pai.\n\nPara termos nós com ele franca e doce comunhão,\nCristo, o Filho, fez-se carne, fez-se nossa redenção!\nPara que na glória eterna o vejamos já sem véu,\nCristo padeceu a morte, o caminho abrindo ao céu.\n',
    'NC 14 - Louvor e Exaltação \n\n Vamos nós louvar a Deus, vamos! Vamos!\nAo Senhor de toda a luz, santo! Santo!\nCantem, louvem lá nos céus nosso Deus e Rei Jesus!\nExaltado seja Deus, santo! Santo!\n\nNosso Deus, eterno Pai, santo! Santo!\nDeu-nos bênçãos por Jesus, vede! Vede!\nAo Senhor glorificai, vós, os salvos pela cruz,\nSim, conosco glória dai, vinde! Vinde!\n\nExaltemos nosso Deus, santo! Santo!\nExaltemos com fervor, hoje! Hoje!\nTributemos, todos nós, hinos santos de louvor,\nSim, louvor em alta voz, hoje! Hoje!\n',
    'NC 15 - Doxologia \n\n Tua, ó Deus, é toda a grandeza\nE o poder e a glória e a vitória\nE os louvores; vitória e louvores!\nTua, ó Deus, tua, ó Deus, é a grandeza\nE o poder, a grandeza e o poder\nE a glória e a vitória e os louvores eternos.\nPois tudo o que está no mar,\nE está no céu e na terra é teu!\nTeu é o domínio, teu é o domínio,\nÓ Senhor! E tu és acima de todos os reis,\nDe todos os reis. Amém. Amém. Aleluia!\n',
    'NC 16 - Louvor ao Deus Soberano \n\n Louvai a Deus, soberano Senhor do que é feito.\nLouvai-o, sim, de vossa alma, tesouro perfeito!\nA Deus cantai e, com fervor, tributai\nProfundo amor e respeito.\n\nLouvai a Deus que vos faz prosperar dia a dia\nE, com amor, vos defende e abençoa a porfia.\nLembrai, também, que o poderoso vos vem\nFazer feliz companhia.\n',
    'NC 17 - Deus Seja Louvado \n\n Seja louvado o Deus supremo,\nDeus adorado em Israel!\nOnipotente, prodígios obra,\nSempre clemente, sempre fiel.\n\nLouvor perene só Deus merece!\nCantai, não cesse o seu louvor!\nDe todos seja sempre exaltado,\nE cante a igreja com terno amor.\n',
    'NC 18 - Deus dos Antigos \n\n Deus dos antigos, cuja forte mão\nRege e sustém os astros na amplidão!\nÓ soberano, excelso Criador,\nCom gratidão cantamos teu louvor!\n\nDesde o passado foste nossa luz,\nSol que até hoje com fulgor reluz!\nSê nosso Esteio, Guia e Proteção,\nTua Palavra, lei e direção.\n\nDa guerra atroz, do crime e assolação,\nDos tempos maus de um mundo em confusão,\nSeja teu braço o nosso defensor,\nPois confiamos sempre em ti, Senhor!\n\nTeu povo, ó Deus, assiste em seu labor,\nNo testemunho do teu grande amor,\nAs nossas vidas vem fortalecer\nPara o teu nome sempre engrandecer. Amém.\n',
    'NC 19 - Rei Sublime \n\n Ó Rei sublime em majestade e glória,\nSobre as milícias do celeste além,\nOuve o louvor, os hinos de vitória,\nDos que de ti recebem todo o bem!\n\nDos altos céus louvor a Deus ressoa,\nDe gratidão ao soberano amor!\nOs redimidos com fervor entoam\nO nome excelso de seu Benfeitor.\n\nEterno Deus, teus filhos vês prostrados\nPerante o brilho da superna luz,\nPois do pecado foram resgatados,\nE agora rendem glórias a Jesus!\n',
    'NC 20 - Glorificação à Trindade \n\n A. Louvor\nA ti, ó Deus, louvamos,\nE por nosso Senhor te confessamos!\nA ti, ó Pai da Eternidade, adora toda a terra;\nA ti, o coro angélico, a ti, todo o poder do céu,\nA ti, querubins e serafins proclamam sem cessar;\n“Santo! Santo! Santo! Senhor Deus dos Exércitos!\nOs céus e a terra estão cheios\nDa majestade da tua glória!”\nA ti, o glorioso coro apostólico louva;\nA ti, a congregação dos profetas louva;\nA ti, o nobre exército dos mártires louva;\nA santa igreja reconhece por toda a terra a ti:\nAo Deus Pai, infinito Dominador!\nE ao teu venerável, vero e único Filho,\nE ao Santo Espírito, Consolador.\n\nB. Declaração\nTu és Rei da Glória, ó Jesus!\nTu és o sempiterno Filho de Deus!\nQuando vieste resgatar os homens,\nNão te escusaste a nascer do ventre da Virgem!\nQuando venceste a morte e seu aguilhão,\nLogo abriste a teus servos\nAs portas do reino dos céus.\nEstás sentado à destra de Deus no trono onipotente.\nCremos que voltarás e aqui serás Juiz.\nPortanto, nós, remidos com teu sangue,\nSuplicamos teu auxílio!\nNós, que já estamos alistados com teus santos\nNa glória eterna.\n\nC. Oração\nSenhor, guarda o povo e abençoa-nos.\nReina e guarda-nos para sempre.\nNoite e dia te adoramos\nE glorificamos teu nome sem par.\nSenhor, concede que hoje\nNós vençamos o pecado!\nEterno e bondoso Pai, compadece-te de nós!\nConcede-nos a tua misericórdia,\nPois confiamos e esperamos em ti.\nSenhor! Em ti, em ti eu espero;\nNunca eu seja, nunca eu seja confundido. Amém.\n',
    'NC 21 - Louvor ao Deus de Abraão \n\n Ao Deus de Abraão louvai, do vasto céu Senhor,\nEterno e poderoso Pai e Deus de amor!\nAugusto Jeová que terra e céu criou,\nMinha alma o Nome exaltará do grande Eu-Sou.\n\nAo Deus de Abraão louvai! Eis, por mandado seu,\nMinha alma deixa a terra e vai gozar no céu.\nO mundo desprezei, seu lucro e seu louvor,\nE Deus por meu quinhão tomei e protetor.\n\nMeu guia Deus será! Seu infinito amor\nFeliz em tudo me fará por onde eu for.\nTomou-me pela mão, na trevas deu-me luz,\nE dá-me eterna salvação por meu Jesus.\n\nMeu Deus por si jurou, eu nele confiei,\nE para o céu que preparou eu subirei.\nSua face eu hei de ver, confiado em seu amor,\nE para sempre engrandecer meu Redentor.\nMeu quinhão; minha parte.\n',
    'NC 22 - A Revelação de Deus \n\n Altamente os céus proclamam seu divino Criador!\nAnuncia o firmamento tuas obras, ó Senhor!\nIncessantes, noite e dia dão sinais do teu poder;\nSem palavras, proclamando Deus excelso no saber!\n\nMajestoso, o sol caminha pelos céus, com resplendor!\nExultando em seu percurso, enche o mundo de calor.\nTodo o vasto universo canta, em coro, teu louvor!\nE a nós vem doce ensino da Palavra do Senhor.\n\nTua Lei — quão preciosa! — brilha mais que a clara luz;\nEsclarece as nossas mentes, guia as almas a Jesus,\nEm tua graça meditando, cantarei, ó bom Senhor,\nE será na minha boca agradável o teu louvor.\nAmém.\n',
    'NC 23 - Adoração ao Criador e Salvador \n\n Oh! Vinde adorar ao Deus Criador,\nDa terra e dos céus, eterno Senhor.\nAo Deus que, habitando no reino da luz,\nA nós se revela por Cristo Jesus.\n\nSeu grande poder deveis contemplar\nNo céu estrelado, no amplo mar.\nA gota de orvalho, a mínima flor,\nProclamam, constantes, ser Deus seu Autor.\n\nOh! Vinde adorar ao Deus Salvador\nQue, em Cristo Jesus, nos mostra favor.\nAo Deus que, benigno, com graça e perdão,\nPecados cobrindo nos dá redenção.\n',
    'NC 24 - Convite ao Louvor \n\n Vinde, irmãos, louvar a Deus,\nCriador da terra e céus.\n\nGlória e honra ao grande Rei;\nAlta e santa é sua lei.\n\nAge com poder real,\nCom grandeza divinal.\n\nDia e noite a sua mão\nDesenvolve o tenro grão.\n\nCom os dons do seu poder\nNossa vida faz crescer.\n',
    'NC 25 - Exaltação ao Criador e Salvador \n\n Deus, do infinito o Criador,\nQue deste aos astros seu fulgor,\nTuas obras te proclamam!\nAo explorarmos a amplidão,\nObra sem par da tua mão,\nExtasiados te louvamos!\nAleluia! Aleluia! Aleluia!\n\nErgue-se o homem para o céu,\nDeixa o planeta em que nasceu;\nOh! Conquista sem limites!\nComo haveremos de entender\nQue Deus quisesse aqui viver?\nDeus eterno, entre os homens!\nAleluia! Aleluia! Aleluia!\n\nHoje há problemas entre nós,\nPor não ouvirmos tua voz.\nPai, perdoa as nossas faltas!\nQue nossa vida em Jesus\nBusque guarida, paz e luz,\nE teu nome celebremos:\nAleluia! Aleluia! Aleluia!\n\nNo grande plano divinal,\nDessa harmonia universal,\nDeus com grande amor salvou-nos!\nEle nos deixa conhecer\nToda a extensão do seu poder\nRevelado no universo!\nAleluia! Aleluia! Aleluia!\n',
    'NC 26 - Louvor ao Deus Grandioso \n\n Senhor meu Deus, quando eu, maravilhado,\nOs grandes feitos vejo da tua mão,\nEstrelas, mundos e trovões rolando,\nA proclamar teu nome na amplidão,\n\nQuando atravesso bosques e florestas\nOuvindo, à brisa, pássaros cantar,\nOu vejo, além, montanhas altaneiras\nO teu poder e glória proclamar;\n\nQuando percebo que, na cruz maldita,\nPor teu amor, Jesus morreu por mim\nE me livrou do jugo do pecado,\nAli vertendo sangue carmesim;\n\nQuando, afinal, em resplendor e glória,\nJesus abrir as portas da mansão,\nEu hei de estar de joelhos entre os santos,\nNa mais humilde e vera adoração,\n',
    'NC 27 - Um Hino ao Senhor \n\n As grutas, as rochas imensas,\nDos mundos o grande esplendor,\nProclamam bem alto, constantes\nUm hino ao teu Nome, Senhor!\n\nNos céus, as estrelas brilhantes,\nDos mares o grande fragor,\nE as brisas entoam, ridentes,\nUm hino ao teu Nome, Senhor!\n\nAs aves alegres, na mata,\nPor entre as ramagens em flor,\nExultam em coro, cantando\nUm hino ao teu Nome, Senhor!\n\nE tu, pecador que vagueias,\nQue fazes ao teu Criador?\nNão achas momento em que cantes\nUm hino de glória ao Senhor?\n',
    'NC 28 - Celebração de Nosso Rei e Sustentador \n\n Tuas obras te coroam\nComo um halo de esplendor!\nAstros, anjos, céus entoam\nHino eterno a ti, Senhor!\nCampos, matas, vales, montes,\nVerde outeiro e verde mar,\nAves e sonoras fontes\nFormam coro singular!\n\nNós, mortais, por ti remidos,\nDeus de glória, Deus de amor,\nCorações aos céus erguidos,\nCelebramos teu louvor!\nRevelaste amor profundo,\nInsondável, sem igual,\nEnviando Cristo ao mundo\nA vencer por nós o mal!\n\nFonte és de alegria e vida,\nÉs do bem o Inspirador;\nTua graça nos convida\nA viver em mútuo amor\nQuais alegres peregrinos,\nSempre em marcha triunfal,\nCantaremos gratos hinos\nNa jornada, até ao final!\n',
    'NC 29 - Adoração ao Nosso Deus Sustentador \n\n Ó minha alma, a Deus bendize\nEm humilde adoração,\nNada há mais que te escravize\nNo pecado e escuridão!\nOh! Louvai-o! Oh! Louvai-o!\nEle é o Rei da criação!\n\nPelo seu favor e graça\nQue outorgou a nossos pais,\nE por tudo que ele faça,\nBendizei-o mais e mais!\nOh! Louvai-o! Oh! Louvai-o!\nComo nossos ancestrais.\n\nSe estivermos em perigo,\nNosso Deus nos guardará;\nEle as trevas e o inimigo\nPara sempre abaterá!\nOh! Louvai-o! Oh! Louvai-o!\nPelas bênçãos que nos dá!\n\nAnjos e homens, reverentes,\nAdorai-o com fervor;\nLua, estrelas, sol luzente,\nQue ao espaço dais fulgor!\nOh! Louvai-o! Oh! Louvai-o!\nPois é Deus de excelso amor!\n',
    'NC 30 - Providência de Deus (na Criação) \n\n Ó Deus! Ó Providência! Com teu real poder\nTrouxeste à existência o mundo, todo ser!\nE a tudo que criaste com benfazeja mão,\nAs bênçãos não negaste da tua proteção.\n\nAo sol resplandecente e à vastidão do mar\nTraçaste, ó Deus potente, as leis que irão guardar.\nE a tenra e pequenina florzinha em botão,\nA tua mão divina conserva em proteção.\n\nDos campos, a verdura, dos frutos, o sabor,\nCelebram a ternura do teu constante amor!\nE a natureza inteira, por toda a Criação,\nProclama, alvissareira, a tua proteção.\nAmém.\n',
    'NC 31 - Providência de Deus (na Redenção) \n\n Ó Deus! Ó Providência! Sem ti não há viver!\nVem dar-nos a assistência do teu real poder!\nTão-só em ti confiamos e em tua proteção,\nPois só em ti achamos conforto e redenção.\n\nAo homem tu criaste, de ti vivo exemplar;\nNa terra o colocaste a fim de te louvar.\nCaído embora esteja, estendes tua mão,\nNa graça benfazeja de tua Redenção.\n\nEm Cristo, o Filho amado, a tua graça vem\nCobrir-nos o pecado e dar-nos todo o bem.\nReais munificências fruímos nós, então,\nNas ternas providências da tua Redenção.\nAmém.\n',
    'NC 32 - O Deus Fiel às Suas Promessas \n\n Tu és fiel, Senhor, ó Pai celeste,\nTeus filhos sabem que não falharás!\nNunca mudaste, tu nunca faltaste,\nTal como eras tu sempre serás.\n\nFlores e frutos, montanhas e mares,\nSol, lua, estrelas brilhando no céu,\nTudo criaste na terra e nos ares,\nPara louvar-te, Senhor, que és fiel.\n\nPleno perdão tu dás! Que segurança!\nCada momento me guias, Senhor,\nE no porvir, oh! Que doce esperança,\nDesfrutarei do teu rico favor.\nAmém.\n',
    'NC 33 - Maravilhas Divinas \n\n Ao Deus de amor e de imensa bondade,\nCom voz de júbilo, vinde e aclamai!\nCom coração transbordante de graças,\nSeu grande amor, todos, vinde e louvai.\n\nJá nossos pais nos contaram a história\nDe Deus, falando com muito prazer\nQue, nas tristezas, nos grandes perigos,\nEle os salvou por seu grande poder.\n\nHoje, também, nós, bem alto, cantamos\nQue as orações ele nos atendeu;\nSeu forte braço, que é tão compassivo,\nEm nosso auxílio ele sempre estendeu.\n\nComo até hoje e daqui para frente\nEle será nosso eterno poder,\nNosso castelo bem forte e seguro\nE nossa fonte de excelso prazer.\n',
    'NC 34 - Louvor ao Deus da Graça \n\n Demos com alegre som\nGlória a Deus, porque ele é bom.\n\nCom poder ele ordenou\nE no mundo a luz raiou.\n\nCom olhar de compaixão\nViu a nossa perdição.\n\nO seu povo abençoou,\nNo deserto ele o guiou.\n\nDemos com alegre som\nGlória a Deus, porque ele é bom.\n',
    'NC 35 - Adoração e Súplica \n\n Teu culto agora, aqui, Senhor,\nNós vimos celebrar,\nCantando, juntos, teu louvor,\nTeu livro a meditar.\n\nÀ nossa vera adoração\nPresente estás, Senhor,\nFazendo o nosso coração\nSentir teu grande amor.\n\nAtende nossas petições,\nÓ poderoso Deus!\nConcede aos nossos corações\nAntegozar os céus.\nAmém.\n',
    'NC 36 - Exaltação Universal \n\n De toda a terra e das nações,\nLouvor a Cristo entoai!\nEm alta voz, dos corações,\nO Nome de Jesus cantai.\n\nEm toda língua bendizei\nA Deus, autor da Criação!\nEm toda a terra engrandecei\nJesus que trouxe a redenção!\n',
    'NC 37 - O Santo Nome \n\n Jesus, teu Nome é santo, amável teu querer.\nLouvor supremo e puro amor queremos te render!\nPoder e honra e glória a ti nós vimos tributar\nE, com sincera devoção, teu culto celebrar!\n\nJesus, teu nome é santo, merece o nosso amor!\nÉs nosso Deus que estás nos céus e nosso protetor.\nIncomparável és, Senhor, em tua compaixão;\nQuiseste, para o mal vencer, fazer-se nosso irmão!\n\nJesus, teu nome é santo, venceste sobre a cruz!\nO teu sofrer, o teu penar, à vida nos conduz.\nGlorificado estás nos céus, atento à adoração\nQue vimos nós, fiéis, prestar com grato coração!\nAmém.\n',
    'NC 38 - Louvores Sem Fim \n\n Mil vezes mil louvores rendamos a Jesus\nQue, da mais alta glória, desceu até à cruz!\nPor sua imensa graça, por seu insigne amor,\nPor todos seja sempre louvado o Salvador.\n\nEis ao redor do trono do Redentor Jesus,\nMilhares de milhares em refulgente luz!\nCom reverência adoram o grande Salvador\nE ao bom Cordeiro rendem a honra e o louvor.\n\nOh! Vinde agora, todos, também a celebrar\nAs glórias sempiternas do Redentor sem par!\nCom vozes de vitória seu Nome proclamai!\nMil vezes mil louvores a Cristo tributai!\n',
    'NC 39 - Exaltação e Louvor \n\n Oh! Vinde crentes dar louvor ao grande rei Jesus\nQue, para a nossa redenção, morreu na amarga cruz;\nSeu sangue derramou, de tudo me lavou,\nMais alvo do que a neve me tornou.\n\nOh! Vinde unir-vos a Jesus na luta contra o mal\nE, com o grande salvador em marcha triunfal,\nA todos proclamar que seu amor sem par\nO fez na cruz seu sangue derramar.\n\nO chefe da milícia é Jesus, meu Salvador,\nO Rei dos reis, o Redentor, o eterno e bom Senhor;\nA tudo vencerá, vitória nos dará\nE à glória eterna os seus conduzirá.\n',
    'NC 40 - Cântico ao Salvador \n\n Cantai a Cristo, o Salvador, que tanto nos amou\nE, para nossa redenção, seu sangue derramou!\n\nCantai o amor celestial, amor do grande Deus,\nDivina flama a consumir os vis pecados meus!\n\nDe Cristo, o excelso, infindo amor, oh! Vinde, publicai!\nE dele a grande salvação a todos proclamai!\n',
    'NC 41 - Louvor Pela Graça Divina \n\n Louvai, louvai Cristo, o bom Mestre divino!\nPor nós na cruz ele sofreu, morreu;\nPerdão, perdão hoje aos contritos outorga,\nPois precioso sangue na cruz verteu.\nSim, louvai-o! Ei-lo tão exaltado,\nMediador que nunca nos faltará.\n\nLouvai, louvai Cristo, o bom Mestre divino!\nConselhos bons dá ele ao pecador;\nAnunciai as bênçãos maravilhosas\nConcedidas por nosso Salvador.\nIde todos, servos de Jesus Cristo,\nE ele nunca vos abandonará.\n\nLouvai, louvai Cristo, o bom Mestre divino!\nCantai, cantai, seu grande amor cantai;\nFiéis, cantai de coração, bem unidos,\nSeu poder e glória louvai, louvai!\nQual pastor que cuida do seu rebanho,\nCristo, assim, os crentes protegerá.\n',
    'NC 42 - O Grande Amor de Deus \n\n A Deus demos glória por seu grande amor:\nO Filho bendito por nós todos deu\nE graça concede ao mais vil pecador,\nAbrindo-lhe a porta de entrada no céu.\n\nOh! Graça real! Foi assim que Jesus,\nMorrendo, seu sangue por nós derramou.\nHerança nos céus, com os santos em luz,\nLegou-nos aquele que o preço pagou.\n\nTal prova de amor nos persuade a confiar\nNos merecimentos do Filho de Deus!\nE quem, a Jesus, pela fé se entregar,\nVai vê-lo na glória eterna dos céus.\n',
    'NC 43 - O Deus de Amor \n\n Desperta já, meu coração e louva ao Salvador,\nCantando em hinos triunfais que Deus é o Deus de amor.\nImenso amor! Amor sem-par! Preenche os vastos céus,\nAlcança a terra e a todos nós, insigne amor de Deus!\n\nAmor que um dia se encarnou a fim de me salvar\nE que, subindo à dura cruz, morreu em meu lugar!\nAmor que exclama: “Vinde a mim!”, que busca o pecador.\nAmor eterno, sem igual, de Cristo, Salvador.\n\nRemido a preço tão real, o sangue do Senhor,\nCom que pagar eu poderei tal graça, tal amor?\nQuando ele a mim, um pecador, se digna de aceitar\nE me levar com seus fiéis ao santo e eterno lar?\n',
    'NC 44 - Louvores ao Senhor \n\n Louvemos ao Senhor, ao Pai da eternidade,\nQue mostra tanto amor à pobre humanidade!\nSeu Filho aqui sofreu por nossa redenção\nE com o Pai nos deu bendita comunhão!\n',
    'NC 45 - Grande Redenção \n\n Milhares de milhares ouço\nCantando a Deus com gratidão,\nA Cristo, o Salvador, louvando\nPor sua grande redenção.\n“A Deus louvai!” — em coro clamam;\n“A Deus louvai — pois nos amou\nE, pelo sangue do Cordeiro,\nDe toda mancha nos lavou!”\n\nO mesmo salmo triunfante,\nEm tons de santa exultação,\nPor todo o mundo vai subindo\nA Deus, autor da redenção.\n“A Deus louvai” — nos vales soa\nE os montes fazem ecoar:\n“A Deus louvai, o Deus da Graça,\nQue aos pecadores quer salvar!”\n\nE nós, teus santos pés cercando,\nEnquanto militando aqui\nAs nossas vozes elevamos\nPara exaltar, Senhor, a ti.\n“A Deus louvai” — também clamamos!\n“A Deus louvai, supremo Rei!\nE glória, honra, majestade\nA Cristo, o Salvador, rendei!”\n\nDas trevas fomos nós chamados\nÀ tua pura e santa luz!\nDa escravidão e do pecado\nNos libertaste pela cruz.\n“A Deus louvai!” — cantemos todos!\n“A Deus louvai, que nos remiu,\nE filhos seus e seus herdeiros,\nEm Cristo, nos constituiu!”\n',
    'NC 46 - Altos Louvores \n\n Altos louvores a quem triunfou!\nJesus, padecendo, seu povo salvou.\nMorto na cruz pelos crimes do mundo,\nDotou aos iníquos de vida e perdão.\nQuão grande esta graça! Favor tão profundo!\nAmor indizível! Real compaixão!\nAltos louvores a quem triunfou!\nJesus, padecendo, seu povo salvou.\n\nGlória rendemos ao bom Salvador,\nExcelso em justiça, supremo em amor!\nCristo quebrou as cadeias do forte,\nSeu cetro arrancando com régio poder.\nAgora, onde estão teus terrores, ó morte?\nSepulcro! Teus presos irão reviver!\nGlória rendemos ao bom Salvador,\nExcelso em justiça, supremo em amor!\n\nGraças te damos, divino Senhor,\nAmparo constante, fiel protetor!\nNunca nos deixas, Pastor incansável!\nTeu braço não falha nem perde o poder.\nConosco presente em bondade imutável,\nTeu povo diriges com alto saber,\nGraças te damos, divino Senhor,\nAmparo constante, fiel protetor!\n\nVem, ó Jesus, majestoso reinar;\nTeu povo te espera, não queiras tardar!\nVem em poder, apressando esse dia,\nPois tua vontade será feita aqui.\nOh! Volta na glória trazendo alegria!\nA igreja suspira, ansiosa, por ti!\nVem, ó Jesus, majestoso reinar;\nTeu povo te espera, não queiras tardar!\n',
    'NC 47 - Louvor e Glória \n\n Louvamos-te, ó Deus, pelo dom de Jesus\nQue, por nós, pecadores, morreu sobre a cruz.\n\nLouvamos-te, ó Deus, pois nos mandas a luz\nQue, brilhando nas trevas, a Cristo conduz.\n\nLouvamos-te, ó Deus, por teu Filho, Jesus,\nQue foi morto, mas vive no Reino da luz.\n\nLouvamos-te, ó Deus, e rogamos, Senhor:\nDá-nos sempre sentir teu poder, teu amor.\n',
    'NC 48 - Amor e Gratidão \n\n Jesus, quão infinito é teu divino amor!\nAlém do nosso alcance, profundo é seu valor!\nOs céus por nós deixaste, vieste, aqui, morrer,\nA fim de que possamos contigo, além, viver.\n\nPor isso, alegremente, buscamos sempre a ti,\nVisando obedecer-te na vida breve aqui.\nEmbora desprezados, com aflições e dor,\nÉ suave e bom servir-te, bendito Salvador!\nAmém.\n',
    'NC 49 - Sempre Vencendo \n\n Sempre vencendo, mui vitorioso,\nCristo Jesus, o Senhor!\nÉ soberano, chefe bendito,\nEm tudo ele é vencedor!\nEi-lo supremo, guiando,\nCom seu imenso poder!\nTodos avante, pois, crentes,\nTodos lutar e vencer.\n\nSempre vencendo, mui vitorioso,\nCristo Jesus, o Senhor!\nEis suas hostes inumeráveis,\nSeu grande império e fulgor;\nEm seu governo demonstra\nCuidado e amor sem igual;\nSempre nos ama e protege\nCom seu poder eternal.\n\nSempre vencendo, mui vitorioso,\nCristo Jesus, o Senhor!\nReis e vassalos, servos e chefes\nQuerem também seu favor.\nSenhor, desejo e te imploro\nQue me permitas lutar\nSempre ao teu lado, invencível,\nAté meus dias findar!\n',
    'NC 50 - Sangue Precioso \n\n Cantarei a Cristo e seu excelso amor;\nPor nós baixou à terra o grande Salvador.\n\nCantarei a Cristo! Por nós morreu na cruz.\nAos pobres pecadores quem salva é só Jesus!\n\nCantarei a Cristo! Por nós cumpriu a lei!\nSeu manto de justiça, alegre, vestirei.\n\nCantarei a Cristo! Nas nuvens voltará\nE na celeste glória os seus receberá.\n',
    'NC 51 - Adoração ao Cordeiro Vencedor \n\n A Cristo adorai, Cordeiro vencedor!\nOuvi das hostes celestiais, dos anjos, o louvor!\nEleva a tua voz e entoa, coração,\nLouvando aquele que morreu e deu-te a salvação.\n\nA Cristo adorai, seu lado e mãos olhai!\nDas suas chagas o esplendor e a glória contemplai!\nNem anjos lá do céu o podem suportar;\nPerante o místico esplendor abaixam seu olhar.\n\nA Cristo adorai! A vida nos doou\nE, a fim de dar-nos salvação, da tumba triunfou!\nCantemos seu poder: morreu, mas ressurgiu!\nA vida eterna ali nos deu e a morte destruiu.\n\nA Cristo adorai, das eras o Senhor,\nDos mundos e astros da amplidão eterno Criador.\nAo grande Redentor que nos deu salvação,\nEternamente tributai louvor e adoração.\n',
    'NC 52 - Glória e Celebração \n\n Saudai o nome de Jesus! Arcanjos, adorai!\nAo Rei que se humilhou na cruz\nCom glória coroai!\n\nÓ escolhida geração de Deus, o eterno Pai,\nAo grande Autor da Salvação\nCom glória coroai!\n\nRemidos todos, com fervor, louvores entoai!\nAo que da morte é vencedor\nCom glória coroai!\n\nÓ raças, povos e nações, ao Rei divino honrai!\nA quem quebrou os vis grilhões\nCom glória coroai!\n',
    'NC 53 - Honra, Poder, Majestade \n\n Honra, poder, majestade, riqueza,\nSabedoria, domínio e grandeza\nAo vencedor da batalha é cantado,\nAo ser, no trono do céu coroado.\n\nSoa nos céus o triunfo, a vitória;\nVibra na terra do seu Nome a glória;\nMontes, oceanos, florestas e flores,\nDo seu domínio ecoam louvores.\n\nSobe em canto constante alegria;\nBênçãos do alto nos vêm cada dia;\nHonra, poder, majestade entoamos\nEm nossos hinos que a Deus elevamos.\n\nDai ao Cordeiro o louvor que é devido;\nNo trono reina de glória vestido.\nFoi imolado — aparente fraqueza!\nMas, triunfante, já vive em grandeza.\n',
    'NC 54 - A Chegada do Messias \n\n Cantai! Exultai! O Messias chegou!\nDissiparam-se as trevas, a aurora raiou!\n\nCantai! Exultai! Pelos ímpios sofreu!\nSatisfez a justiça e o sangue verteu!\n\nCantai! Exultai! Temos pleno perdão,\nPois Jesus nos concede real salvação!\n\nCantai! Exultai! Jesus Cristo, nos céus,\nPelos seus intercede à destra de Deus.\n\nCantai! Exultai! O Senhor voltará!\nTriunfante, glorioso, nas nuvens virá!\n',
  ],
  lawReading: [
    'NC 033 · Maravilhas Divinas',
    'NC 067 · Coração Quebrantado',
    'NC 078 · Perfeita Expiação',
    'NC 121 · Perfeição',
    'NC 131 · Vida Santificada',
    'NC 133 · Aspiração à Santidade',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
    'NC 371 · A Bíblia',
    'NC 372 · O Crente e a Bíblia',
  ],
  forgiveness: [
    'NC 058 · Ofertas',
    'NC 062 · Hino de Gratidão',
    'NC 063 · As Muitas Bênçãos',
    'NC 066 · Contrição',
    'NC 067 · Coração Quebrantado',
    'NC 068 · Dependência de Deus',
    'NC 069 · Súplica',
    'NC 070 · Descanso em Jesus',
    'NC 071 · Contrição e Confissão',
    'NC 072 · Purificação',
    'NC 073 · Compaixão',
    'NC 074 · Sinceridade',
    'NC 075 · Arrependimento e Súplica',
    'NC 076 · Clamor por Compaixão',
    'NC 077 · Divino Perdão',
    'NC 078 · Perfeita Expiação',
    'NC 089 · Amor Insondável',
    'NC 096 · Redenção Suprema',
    'NC 098 · Não Há Condenação',
    'NC 103 · Salvação em Cristo',
    'NC 106 · Fonte Carmesim',
    'NC 222 · Mais Perto da Cruz',
    'NC 223 · Oração do Arrependido',
  ],
  intercession: [
    'NC 055 · Alegria e Gratidão',
    'NC 056 · Ações de Graças e Súplica',
    'NC 057 · Fonte de Todo Bem',
    'NC 058 · Ofertas',
    'NC 059 · Gratidão',
    'NC 060 · Ofertório',
    'NC 061 · Ações de Graças',
    'NC 062 · Hino de Gratidão',
    'NC 063 · As Muitas Bênçãos',
    'NC 064 · Grata Memória',
    'NC 065 · Gratidão e Louvor',
    'NC 086 · Oração ao Espírito Santo',
    'NC 087 · Alegria Perene',
    'NC 129 · Vigilância e Oração',
    'NC 130 · Oração ao Senhor',
    'NC 140 · Jornada do Crente',
    'NC 148 · Oração Noturna',
    'NC 175 · O Servo do Senhor',
    'NC 176 · Fidelidade do Cristão',
    'NC 178 · A Excelência do Amor',
    'NC 225 · O Pai Nosso',
  ],
  illumination: [
    'NC 082 · Divino Preceptor',
    'NC 083 · Divino Instruidor',
    'NC 084 · Santo Espírito',
    'NC 085 · Espírito Consolador',
    'NC 086 · Oração ao Espírito Santo',
    'NC 137 · Abrigo no Temporal',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
    'NC 352 · Leitura Bendita',
    'NC 371 · A Bíblia',
    'NC 372 · O Crente e a Bíblia',
  ],
  wordPreaching: [
    'NC 080 · O Amor de Jesus',
    'NC 081 · Súplica ao Espírito Santo',
    'NC 082 · Divino Preceptor',
    'NC 083 · Divino Instruidor',
    'NC 084 · Santo Espírito',
    'NC 095 · Somente Cristo',
    'NC 114 · Brilho Celeste',
    'NC 124 · Benigna Luz',
    'NC 154 · Segurança e Paz',
    'NC 160 · Cristo é Tudo',
    'NC 164 · Nome Precioso',
    'NC 177 · Firme nas Promessas',
    'NC 266 · Rude Cruz',
    'NC 301 · O Único Salvador',
    'NC 305 · Quem Quiser',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
  ],
  lordsSupper: [
    'NC 094 · A Porta da Salvação',
    'NC 095 · Somente Cristo',
    'NC 112 · Rica Promessa',
    'NC 147 · Vencendo Vem Jesus',
    'NC 190 · Maior Que a Dor',
    'NC 267 · Precioso Sangue',
    'NC 340 · Santa Comunhão',
    'NC 341 · Vera Páscoa',
    'NC 342 · Comunhão',
    'NC 343 · Em Memória',
    'NC 344 · A Ceia do Senhor',
    'NC 345 · O Pão do Mundo',
    'NC 346 · A Ceia do Senhor',
  ],
  consecration: [
    'NC 095 · Somente Cristo',
    'NC 119 · Súplica pelo Culto',
    'NC 120 · Dependência',
    'NC 135 · Mais de Cristo',
    'NC 176 · Fidelidade do Cristão',
    'NC 207 · Convite ao Pecador',
    'NC 217 · Desprendimento',
    'NC 219 · Dedicação',
    'NC 220 · Plena Dedicação',
    'NC 221 · Um Vaso de Benção',
    'NC 224 · Consagração',
    'NC 225 · Dedicação Pessoal',
    'NC 315 · Serviço do Crente',
    'NC 316 · Os Intentos de Deus',
    'NC 317 · Chamada',
    'NC 318 · Ceifeiros do Senhor',
    'NC 319 · Obreiros em Marcha',
    'NC 320 · Brilha no Viver',
    'NC 321 · Mãos ao Trabalho',
  ],
  sending: [
    'NC 170 · Redentor Onipotente',
    'NC 171 · Deus Proverá',
    'NC 208 · Aproximação',
    'NC 225 · Dedicação Pessoal',
    'NC 282 · A Grande Comissão',
    'NC 283 · Avançar com Jesus',
    'NC 284 · Obediência',
    'NC 287 · Igreja, Alerta!',
    'NC 288 · A Mensagem Real',
    'NC 289 · Quem Irá?',
    'NC 299 · Renovação',
    'NC 300 · Igreja Militante',
    'NC 304 · A Voz do Evangelho',
    'NC 311 · Avante, ó Crentes',
    'NC 320 · Brilha no Viver',
  ],
  blessing: [
    'NC 005 · Trindade Adorada',
    'NC 150 · Salvação Perfeita',
    'NC 168 · Jesus Amado',
    'NC 226 · A História de Cristo',
    'NC 320 · Brilha no Viver',
    'NC 368 · Despedida',
    'NC 398 · Outra Vez Cantamos',
    'NC 399 · Término do Culto',
    'NC 400 · Oração por Proteção',
  ],
};
