
// Sugestões de hinos do Novo Cântico organizados por seção litúrgica
export const hymnSuggestions = {
  worshipCall: [
    'NC 001 · Doxologia',
    'NC 002 · Reverência',
    'NC 003 · A Igreja em Adoração',
    'NC 004 · Culto à Trindade',
    'NC 010 · A Criação e Seu Criador',
    'NC 014 · Louvor e Exaltação',
    'NC 017 · Deus Seja Louvado',
    'NC 019 · Rei Sublime',
    'NC 021 · Louvor ao Deus de Abraão',
    'NC 022 · A Revelação de Deus',
    'NC 024 · Convite ao Louvor',
    'NC 025 · Exaltação ao Criador e Salvador',
    'NC 026 · Louvor ao Deus Grandioso',
    'NC 036 · Exaltação Universal',
    'NC 038 · Louvores Sem Fim',
    'Salmo 8 - Ó Senhor, quão maravilhoso',
    'Salmo 100 - Celebrai com júbilo ao Senhor',
  ],
  lawReading: [
    'NC 033 · Maravilhas Divinas',
    'NC 067 · Coração Quebrantado',
    'NC 078 · Perfeita Expiação',
    'NC 121 · Perfeição',
    'NC 131 · Vida Santificada',
    'NC 133 · Aspiração à Santidade',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
    'NC 371 · A Bíblia',
    'NC 372 · O Crente e a Bíblia',
    'Salmo 19 - Os céus proclamam',
    'Salmo 119 - Lâmpada para os meus pés',
  ],
  forgiveness: [
    'NC 058 · Ofertas',
    'NC 062 · Hino de Gratidão',
    'NC 063 · As Muitas Bênçãos',
    'NC 066 · Contrição',
    'NC 067 · Coração Quebrantado',
    'NC 071 · Contrição e Confissão',
    'NC 072 · Purificação',
    'NC 074 · Sinceridade',
    'NC 075 · Arrependimento e Súplica',
    'NC 076 · Clamor por Compaixão',
    'NC 077 · Divino Perdão',
    'NC 078 · Perfeita Expiação',
    'NC 089 · Amor Insondável',
    'NC 096 · Redenção Suprema',
    'NC 098 · Não Há Condenação',
    'NC 103 · Salvação em Cristo',
    'NC 106 · Fonte Carmesim',
    'NC 222 · Mais Perto da Cruz',
    'NC 223 · Oração do Arrependido',
    'Salmo 32 - Bem-aventurado',
    'Salmo 51 - Tem misericórdia de mim',
  ],
  intercession: [
    'NC 086 · Oração ao Espírito Santo',
    'NC 087 · Alegria Perene',
    'NC 129 · Vigilância e Oração',
    'NC 130 · Oração ao Senhor',
    'NC 140 · Jornada do Crente',
    'NC 148 · Oração Noturna',
    'NC 175 · O Servo do Senhor',
    'NC 176 · Fidelidade do Cristão',
    'NC 178 · A Excelência do Amor',
    'NC 225 · O Pai Nosso',
    'Salmo 20 - O Senhor te ouça',
    'Salmo 130 - Das profundezas',
  ],
  illumination: [
    'NC 082 · Divino Preceptor',
    'NC 083 · Divino Instruidor',
    'NC 084 · Santo Espírito',
    'NC 085 · Espírito Consolador',
    'NC 086 · Oração ao Espírito Santo',
    'NC 137 · Abrigo no Temporal',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
    'NC 352 · Leitura Bendita',
    'NC 371 · A Bíblia',
    'NC 372 · O Crente e a Bíblia',
    'Salmo 19 - A lei do Senhor é perfeita',
    'Salmo 119 - Como o jovem manterá puro o seu caminho',
  ],
  wordPreaching: [
    'NC 080 · O Amor de Jesus',
    'NC 081 · Súplica ao Espírito Santo',
    'NC 082 · Divino Preceptor',
    'NC 083 · Divino Instruidor',
    'NC 084 · Santo Espírito',
    'NC 095 · Somente Cristo',
    'NC 114 · Brilho Celeste',
    'NC 124 · Benigna Luz',
    'NC 154 · Segurança e Paz',
    'NC 160 · Cristo é Tudo',
    'NC 164 · Nome Precioso',
    'NC 177 · Firme nas Promessas',
    'NC 266 · Rude Cruz',
    'NC 301 · O Único Salvador',
    'NC 305 · Quem Quiser',
    'NC 350 · A Palavra da Vida',
    'NC 351 · Belas Palavras de Vida',
  ],
  lordsSupper: [
    'NC 094 · A Porta da Salvação',
    'NC 095 · Somente Cristo',
    'NC 112 · Rica Promessa',
    'NC 147 · Vencendo Vem Jesus',
    'NC 190 · Maior Que a Dor',
    'NC 267 · Precioso Sangue',
    'NC 340 · Santa Comunhão',
    'NC 341 · Vera Páscoa',
    'NC 342 · Comunhão',
    'NC 343 · Em Memória',
    'NC 344 · A Ceia do Senhor',
    'NC 345 · O Pão do Mundo',
    'NC 346 · A Ceia do Senhor',
    'Salmo 116 - Que darei ao Senhor',
  ],
  consecration: [
    'NC 095 · Somente Cristo',
    'NC 119 · Súplica pelo Culto',
    'NC 120 · Dependência',
    'NC 135 · Mais de Cristo',
    'NC 176 · Fidelidade do Cristão',
    'NC 207 · Convite ao Pecador',
    'NC 217 · Desprendimento',
    'NC 219 · Dedicação',
    'NC 220 · Plena Dedicação',
    'NC 221 · Um Vaso de Benção',
    'NC 224 · Consagração',
    'NC 225 · Dedicação Pessoal',
    'NC 315 · Serviço do Crente',
    'NC 316 · Os Intentos de Deus',
    'NC 317 · Chamada',
    'NC 318 · Ceifeiros do Senhor',
    'NC 319 · Obreiros em Marcha',
    'NC 320 · Brilha no Viver',
    'NC 321 · Mãos ao Trabalho',
    'Salmo 116 - Que darei ao Senhor',
  ],
  sending: [
    'NC 170 · Redentor Onipotente',
    'NC 171 · Deus Proverá',
    'NC 208 · Aproximação',
    'NC 225 · Dedicação Pessoal',
    'NC 282 · A Grande Comissão',
    'NC 283 · Avançar com Jesus',
    'NC 284 · Obediência',
    'NC 287 · Igreja, Alerta!',
    'NC 288 · A Mensagem Real',
    'NC 289 · Quem Irá?',
    'NC 299 · Renovação',
    'NC 300 · Igreja Militante',
    'NC 304 · A Voz do Evangelho',
    'NC 311 · Avante, ó Crentes',
    'NC 320 · Brilha no Viver',
    'Salmo 67 - Deus tenha misericórdia',
  ],
  blessing: [
    'NC 150 · Salvação Perfeita',
    'NC 168 · Jesus Amado',
    'NC 226 · A História de Cristo',
    'NC 320 · Brilha no Viver',
    'NC 368 · Despedida',
    'NC 398 · Outra Vez Cantamos',
    'NC 399 · Término do Culto',
    'NC 400 · Oração por Proteção',
    'Salmo 121 - O Senhor é teu guarda',
    'Salmo 134 - Bendizei ao Senhor',
  ],
};
